import { describe, it, expect, vi, beforeEach } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';

/**
 * PWA manifest is now generated by vite-plugin-pwa in vite.config.ts.
 * These tests validate the config values by reading the vite config source.
 */
describe('PWA Manifest (vite-plugin-pwa)', () => {
  let viteConfig: string;

  beforeEach(() => {
    viteConfig = readFileSync(resolve(__dirname, '../../vite.config.ts'), 'utf-8');
  });

  it('has required PWA manifest fields in vite config', () => {
    expect(viteConfig).toContain("name: 'DisinfoDesk: Das Lexikon'");
    expect(viteConfig).toContain("short_name: 'DisinfoDesk'");
    expect(viteConfig).toContain("display: 'standalone'");
    expect(viteConfig).toContain("theme_color: '#020617'");
    expect(viteConfig).toContain("background_color: '#020617'");
  });

  it('has valid icons with required purposes', () => {
    expect(viteConfig).toContain("purpose: 'any'");
    expect(viteConfig).toContain("purpose: 'maskable'");
    expect(viteConfig).toContain('icon.svg');
    expect(viteConfig).toContain('icon-maskable.svg');
  });

  it('icons use local paths (no CDN)', () => {
    // Icons in manifest config should not reference external CDNs
    const iconMatch = viteConfig.match(/icons:\s*\[[\s\S]*?\]/);
    expect(iconMatch).toBeTruthy();
    expect(iconMatch![0]).not.toContain('http://');
    expect(iconMatch![0]).not.toContain('flaticon');
  });

  it('has start_url and scope', () => {
    expect(viteConfig).toContain("start_url: './'");
    expect(viteConfig).toContain("scope: './'");
  });

  it('has description', () => {
    expect(viteConfig).toContain('Ein interaktives Kompendium');
  });

  it('shortcuts use local icons', () => {
    expect(viteConfig).toContain('shortcuts:');
    // All shortcut icons should reference local SVG
    const shortcutsMatch = viteConfig.match(/shortcuts:\s*\[[\s\S]*?\],\s*protocol_handlers/);
    if (shortcutsMatch) {
      expect(shortcutsMatch[0]).not.toContain('http://');
    }
  });
});

describe('Service Worker configuration (vite-plugin-pwa)', () => {
  let viteConfig: string;

  beforeEach(() => {
    viteConfig = readFileSync(resolve(__dirname, '../../vite.config.ts'), 'utf-8');
  });

  it('uses autoUpdate register type', () => {
    expect(viteConfig).toContain("registerType: 'autoUpdate'");
  });

  it('enables skipWaiting + clientsClaim', () => {
    expect(viteConfig).toContain('skipWaiting: true');
    expect(viteConfig).toContain('clientsClaim: true');
  });

  it('cleans up outdated caches', () => {
    expect(viteConfig).toContain('cleanupOutdatedCaches: true');
  });

  it('has runtime caching for Google Fonts', () => {
    expect(viteConfig).toContain('google-fonts-stylesheets');
    expect(viteConfig).toContain('google-fonts-webfonts');
  });

  it('has runtime caching for CDN assets', () => {
    expect(viteConfig).toContain('cdn-assets');
    expect(viteConfig).toContain("handler: 'StaleWhileRevalidate'");
  });

  it('has runtime caching for images', () => {
    expect(viteConfig).toContain('images-cache');
    expect(viteConfig).toContain("handler: 'CacheFirst'");
  });

  it('uses NetworkOnly for AI API calls (security)', () => {
    expect(viteConfig).toContain("handler: 'NetworkOnly'");
    expect(viteConfig).toContain('generativelanguage.googleapis.com');
    expect(viteConfig).toContain('api.x.ai');
    expect(viteConfig).toContain('api.anthropic.com');
  });

  it('configures navigate fallback', () => {
    expect(viteConfig).toContain("navigateFallback: 'index.html'");
  });
});

describe('Offline readiness', () => {
  it('navigator.onLine is available', () => {
    expect(typeof navigator.onLine).toBe('boolean');
  });

  it('online/offline events can be dispatched', () => {
    const handler = vi.fn();
    window.addEventListener('offline', handler);
    window.dispatchEvent(new Event('offline'));
    expect(handler).toHaveBeenCalledOnce();
    window.removeEventListener('offline', handler);
  });

  it('online event fires correctly', () => {
    const handler = vi.fn();
    window.addEventListener('online', handler);
    window.dispatchEvent(new Event('online'));
    expect(handler).toHaveBeenCalledOnce();
    window.removeEventListener('online', handler);
  });
});

describe('index.html meta tags', () => {
  let html: string;

  beforeEach(() => {
    html = readFileSync(resolve(__dirname, '../../index.html'), 'utf-8');
  });

  it('PWA manifest is injected by vite-plugin-pwa at build time', () => {
    // vite-plugin-pwa injects the manifest link; index.html no longer has a static link
    // Verify the plugin is configured in vite.config.ts instead
    const viteConfig = readFileSync(resolve(__dirname, '../../vite.config.ts'), 'utf-8');
    expect(viteConfig).toContain('VitePWA');
  });

  it('has no CDN icon references', () => {
    expect(html).not.toContain('flaticon');
    expect(html).not.toContain('cdn-icons-png');
  });

  it('has apple-touch-icon', () => {
    expect(html).toContain('apple-touch-icon');
  });

  it('has theme-color meta', () => {
    expect(html).toContain('theme-color');
  });

  it('has og:title meta', () => {
    expect(html).toContain('og:title');
  });

  it('has viewport meta for mobile', () => {
    expect(html).toContain('viewport');
    expect(html).toContain('width=device-width');
  });
});
