/**
 * SharedView — Read-Only Anonymized Public View
 * 
 * Renders a shared theory or report from URL params.
 * No API key required. No user data exposed.
 */

import React, { useEffect, useState } from 'react';
import { parseShareLink, exportShareJSON, exportSharePDF, SharePayload } from '../services/shareService';
import { PageFrame, PageHeader, Card, Button, Badge } from './ui/Common';
import { Share2, Download, FileDown, Shield, ExternalLink, AlertTriangle } from 'lucide-react';

export const SharedView: React.FC = () => {
  const [payload, setPayload] = useState<SharePayload | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    const data = parseShareLink();
    if (data) setPayload(data);
    else setError(true);
  }, []);

  if (error) {
    return (
      <PageFrame>
        <div className="flex flex-col items-center justify-center min-h-[60vh] text-center" role="alert">
          <AlertTriangle size={48} className="text-red-500 mb-4" />
          <h2 className="text-xl font-bold text-white mb-2">Invalid Share Link</h2>
          <p className="text-slate-400 text-sm max-w-md">
            This share link is corrupted or expired. Request a new link from the sender.
          </p>
          <a href="#/" className="mt-6 text-accent-cyan hover:underline text-sm">← Back to DisinfoDesk</a>
        </div>
      </PageFrame>
    );
  }

  if (!payload) {
    return (
      <PageFrame>
        <div className="flex items-center justify-center min-h-[40vh]">
          <div className="animate-pulse text-slate-500 font-mono text-sm">Decoding shared payload...</div>
        </div>
      </PageFrame>
    );
  }

  return (
    <PageFrame>
      <PageHeader
        title={payload.title}
        subtitle={`Shared ${payload.type.toUpperCase()} · ${new Date(payload.sharedAt).toLocaleDateString()} · Read-Only`}
        icon={Share2}
        status="READ-ONLY"
        statusColor="bg-yellow-500"
        actions={
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => exportShareJSON(payload)} icon={<Download size={14} />}>JSON</Button>
            <Button variant="ghost" size="sm" onClick={() => exportSharePDF(payload)} icon={<FileDown size={14} />}>PDF</Button>
          </div>
        }
      />

      <div className="space-y-6 max-w-3xl mx-auto">
        {/* Read-Only Banner */}
        <div className="flex items-center gap-3 p-4 rounded-lg bg-yellow-950/30 border border-yellow-600/30">
          <Shield size={20} className="text-yellow-500 shrink-0" />
          <div>
            <p className="text-xs font-bold text-yellow-400 uppercase tracking-wider">Anonymized Public View</p>
            <p className="text-xs text-slate-400 mt-0.5">No API key required. This is a read-only snapshot generated by DisinfoDesk.</p>
          </div>
        </div>

        {/* Summary */}
        {payload.summary && (
          <Card>
            <h3 className="text-xs font-bold text-accent-cyan uppercase tracking-wider mb-3">Summary</h3>
            <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">{payload.summary}</p>
          </Card>
        )}

        {/* Findings */}
        {payload.findings && payload.findings.length > 0 && (
          <Card>
            <h3 className="text-xs font-bold text-accent-cyan uppercase tracking-wider mb-3">Findings</h3>
            <ol className="space-y-2">
              {payload.findings.map((f, i) => (
                <li key={i} className="flex gap-3 text-sm text-slate-300">
                  <Badge label={String(i + 1)} color="red" className="shrink-0 mt-0.5" />
                  <span className="leading-relaxed">{f}</span>
                </li>
              ))}
            </ol>
          </Card>
        )}

        {/* References */}
        {payload.references && payload.references.length > 0 && (
          <Card>
            <h3 className="text-xs font-bold text-accent-cyan uppercase tracking-wider mb-3">References</h3>
            <ul className="space-y-2">
              {payload.references.map((ref, i) => (
                <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                  <ExternalLink size={12} className="text-slate-500 mt-1 shrink-0" />
                  <div>
                    <span>{ref.title}</span>
                    {ref.url && /^https?:\/\//i.test(ref.url) && (
                      <a href={ref.url} target="_blank" rel="noopener noreferrer" className="block text-xs text-accent-cyan hover:underline mt-0.5">
                        {ref.url}
                      </a>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {/* Metadata */}
        <div className="text-center py-6">
          <p className="text-[10px] text-slate-600 font-mono">
            SHARE_VERSION: {payload.version} · TYPE: {payload.type} · ID: {payload.id} · LANG: {payload.lang}
          </p>
          <a href="#/" className="text-xs text-accent-cyan hover:underline mt-2 inline-block">
            ← Open DisinfoDesk
          </a>
        </div>
      </div>
    </PageFrame>
  );
};

export default SharedView;
